server:
  port: 8087

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: client-db
      username: root
      password: Zeeze5775
      authentication-database: admin


management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: @project.name@